#pragma once

#include "quantum.h"


#if defined(NEW_SAFE_RANGE)
#		define OK_KEYCODES_START_RANGE NEW_SAFE_RANGE
#elif defined(KEYMAP_SAFE_RANGE)
#		define OK_KEYCODES_START_RANGE KEYMAP_SAFE_RANGE
#else
#		define OK_KEYCODES_START_RANGE SAFE_RANGE
#endif

enum ok_modes {
  OK_KEYCODES_LINUX_MODE,
	OK_KEYCODES_WINDOWS_MODE,
	OK_KEYCODES_MAC_MODE
};

enum ok_keycodes {
	OK_KEYCODES_FIRST = OK_KEYCODES_START_RANGE,
  OK_KEYCODES_COPY,
  OK_KEYCODES_CUT,
  OK_KEYCODES_PASTE,
  OK_KEYCODES_UNDO,
  OK_KEYCODES_REDO,
  OK_KEYCODES_LOCK,
  OK_KEYCODES_SUSPEND,
  OK_KEYCODES_POWER_DOWN,
  OK_KEYCODES_SCREENSHOT,
  OK_KEYCODES_MULTI_TASK_VIEW,
  OK_KEYCODES_APP_WINDOWS,
  OK_KEYCODES_DESKTOP_NEXT,
  OK_KEYCODES_DESKTOP_PREV,
  OK_KEYCODES_OS_SEARCH,
  OK_KEYCODES_TERMINAL,

	OK_KEYCODES_SET_MODE_LINUX,
	OK_KEYCODES_SET_MODE_WINDOWS,
	OK_KEYCODES_SET_MODE_MAC,

	OK_KEYCODES_END_RANGE
};

#define OK_COPY OK_KEYCODES_COPY
#define OK_CUT OK_KEYCODES_CUT
#define OK_PASTE OK_KEYCODES_PASTE
#define OK_UNDO OK_KEYCODES_UNDO
#define OK_REDO OK_KEYCODES_REDO
#define OK_LOCK OK_KEYCODES_LOCK
#define OK_SUSPEND OK_KEYCODES_SUSPEND
#define OK_POWER_DOWN OK_KEYCODES_POWER_DOWN
#define OK_SCREENSHOT OK_KEYCODES_SCREENSHOT
#define OK_MULTI_TASK_VIEW OK_KEYCODES_MULTI_TASK_VIEW
#define OK_APP_WINDOWS OK_KEYCODES_APP_WINDOWS
#define OK_DESKTOP_NEXT OK_KEYCODES_DESKTOP_NEXT
#define OK_DESKTOP_PREV OK_KEYCODES_DESKTOP_PREV
#define OK_OS_SEARCH OK_KEYCODES_OS_SEARCH
#define OK_TERMINAL OK_KEYCODES_TERMINAL

#define OK_SET_LINUX_MODE OK_KEYCODES_SET_MODE_LINUX
#define OK_SET_WINDOWS_MODE OK_KEYCODES_SET_MODE_WINDOWS
#define OK_SET_MAC_MODE OK_KEYCODES_SET_MODE_MAC

void set_os_mode(uint8_t mode);
uint8_t get_os_mode(void);

bool ok_process_record_user(uint16_t keycode, keyrecord_t *record);

bool ok_process_keycode_linux(uint16_t keycode);
bool ok_process_keycode_windows(uint16_t keycode);
bool ok_process_keycode_mac(uint16_t keycode);
